version: '3.9'
services:
  session-db:
    image: redis:latest
    restart: always
    ports:
      - 6000:6000
    command: redis-server --save 20 1 --port 6000 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - db:/var/lib/redis

  einer-dev:
    build:
      context: ./
      dockerfile: dockerfile.dev
    restart: always
    ports:
      - 3000:3000
      - 5000:5000
      - 5001:5001
    environment:
      - DATABASE_REDIS_URL=redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@session-db:6000
    depends_on:
      - session-db
    links:
      - session-db
    volumes:
      - ./:/einer

volumes:
  db:
    driver: local